<?php
/** @var Aprilo\CommerceAssistant\Block\Widget $block */
if ($block->isWidgetActive()):
    $params = $block->getWidgetParams();
?>
<!-- Aprilo Assistant Widget Load -->
<script>
    (function(w,d,s,o,f,js,fjs){
        w['ApriloAssistant']=o;w[o]=w[o]||function(){(w[o].q=w[o].q||[]).push(arguments)};
        js=d.createElement(s),fjs=d.getElementsByTagName(s)[0];js.id=o;js.src=f;js.async=1;fjs.parentNode.insertBefore(js,fjs);
    }(window,document,'script','aprilo','<?php echo $params['platformUrl']; ?>/widget.js'));
    
    aprilo('init', <?php echo json_encode($params); ?>);
</script>
<?php endif; ?>
